<header class="header-fixed" style=" margin-left:0%; padding-left:0%;">

	<div class="header-limiter" style=" margin-left:0%; padding-left:0%;">
		<h1><img src="<?php echo Mage::getImagePath('')?>"></h1>
		<nav>
        <i class="ri-apple-fill"></i>
        <a id="store" href="">Store</a>
        <a href="">Mac</a>
        <a href="">iPad</a>
        <a href="">iPhone</a>
        <a href="">Watch</a>
        <a href="">AirPods</a>
        <a href="">TV & Home</a>
        <a href="">Entertainment</a>
        <a href="">Accessories</a>
        <a href="">Support</a>
        <i class="ri-search-line"></i>
        <i class="ri-shopping-bag-line"></i>
        <i class="ri-menu-3-line"></i>
      </nav>

	</div>

</header>