<?php
// $this->getOrderCollection();
// print_r(get_class($this));
// die;
// $productItem = $this->getCartItem();
// die;
// $productItems = $this->getCartItem()->getLastItem();
$productItem = $this->getCartItem()->getData();
$id = $this->getRequest()->getparams('id');
// print_r($id);
// $gTotal = 0;
// var_dump(Mage::getSingleton('sales/quote')->getTaxPercent());
// $gTotal += round($gTotal / Mage::getModel('sales/quote')->getTaxPercent(),2);
if ($productItem) { //not needed as now there is empty cart
$gTotal = $this->quoteData()->getLastItem()->getGrandTotal();
}
//   // print_r($gTotal);
// }
// echo '<pre>';
// var_dump($gTotal->getGrandTotal());
// die;
?>

<div class="container px-3 my-5 clearfix">
  <!-- Shopping cart table -->
  <div class="card">
    <div class="card-header">
      <h2>Shopping Cart</h2>
    </div>
    <?php if ($productItem) { ?>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered m-0">
            <thead>
              <tr>
                <!-- Set columns width -->
                <th class="text-center py-3 px-4" style="min-width: 400px;">Product Name &amp; Details</th>
                <th class="text-right py-3 px-4" style="width: 100px;">Price</th>
                <th class="text-center py-3 px-4" style="width: 120px;">Quantity</th>
                <th class="text-right py-3 px-4" style="width: 100px;">Total</th>
                <!-- <th class="text-right py-3 px-4" style="width: 100px;">Row Total</th> -->
                <th class="text-center align-middle py-3 px-0" style="width: 40px;"><a href="#"
                    class="shop-tooltip float-none text-light" title="" data-original-title="Clear cart"><i
                      class="ino ion-md-trash"></i></a></th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($productItem as $product) { ?>
                <tr>
                  <td class="p-4">
                    <div class="media align-items-center">
                      <img
                        src="<?php echo Mage::getImagePath('catalog/product/' . $product->getProduct()->getImageLink()) ?>"
                        class="d-block ui-w-40 ui-bordered mr-4" alt="">
                      <div class="media-body">
                        <a href="<?php echo $this->getUrl('catalog/product/view?id=' . $product->getProductId()) ?>"
                          class="d-block text-dark">
                          <?php echo $product->getProduct()->getName(); ?>
                        </a>
                      <?php
                      
                      if ($this->checkStock($product)) { ?>
                                          <?php //print_r($product)?>
                                                    <p style="color: red">Out of stock</p>
                                            
                                        <?php } ?>
                        <!-- <small>
                            <span class="text-muted">Color:</span>
                            <span class="ui-product-color ui-product-color-sm align-text-bottom" style="background:#e81e2c;"></span> &nbsp;
                            <span class="text-muted">Size: </span> EU 37 &nbsp;
                            <span class="text-muted">Ships from: </span> China
                          </small> -->
                      </div>
                    </div>
                  </td>
                  <td class="text-right font-weight-semibold align-middle p-4">
                    <?php echo $product->getPrice() ?>
                  </td>
                  <form action="<?php echo $this->getUrl('sales/quote/add') ?>" method="post">
                    <td class="align-middle p-4">
                      <input type="text" name="cart[item_id]" hidden value="<?php echo $product->getItemId() ?>">
                      <input type="text" name="cart[quote_id]" hidden value="<?php echo $product->getQuoteId() ?>">
                      <input type="text" name="cart[product_id]" hidden value="<?php echo $product->getProductId() ?>">
                      <input type="number" name="cart[qty]" class="form-control text-center"
                        value="<?php echo $product->getQty(); ?>" min="1"
                        max="<?php echo $product->getProduct()->getStock(); ?>">
                      <input type="submit" name="submit" value="add to cart">
                  </form>
                  <td class="text-right font-weight-semibold align-middle p-4">
                    <?php echo $product->getPrice() * $product->getQty() ?>
                  </td>
                  <td class="text-right font-weight-semibold align-middle p-4" hidden>
                    <?php //echo $gTotal += $product->getPrice() * $product->getQty()  ?>
                  </td>
                  <td class="text-center align-middle px-0"><a
                      href="<?php echo $this->getUrl("sales/quote/delete") ?>?id=<?php echo $product->getItemId() ?>&qid=<?php echo $product->getQuoteId() ?>"
                      class="shop-tooltip close float-none text-danger" title="" data-original-title="Remove">×</a>
                  </td>
                </tr>
              <?php } ?>



            </tbody>
          </table>
        </div>
        <!-- / Shopping cart table -->

        <div class="d-flex flex-wrap justify-content-between align-items-center pb-4">
          <div class="mt-4">
            <!-- <label class="text-muted font-weight-normal">Promocode</label>
                <input type="text" placeholder="ABC" class="form-control"> -->
          </div>
          <div class="d-flex">
            <!-- <div class="text-right mt-4 mr-5">
                  <label class="text-muted font-weight-normal m-0">Discount</label>
                  <div class="text-large"><strong>$20</strong></div>
                </div> -->
            <div class="text-right mt-4">
              <label class="text-muted font-weight-normal m-0">Total price(inc. all tax)</label>
              <div class="text-large"><strong>Rs.
                  <?php echo $gTotal ?>
                </strong></div>
            </div>
          </div>
        </div>

        <div class="float-right">
          <a href='<?php echo $this->getUrl("catalog/product/all") ?>'> <button type="button"
              class="btn btn-lg btn-default md-btn-flat mt-2 mr-3">Back to shopping</button></a>
          <a href='<?php echo $this->getUrl("cart/checkout/checkout") ?>'><button type="button"
              class="btn btn-lg btn-primary mt-2">Checkout</button></a>
        </div>

      </div>
    <?php } else { ?>
      <!-- <script>alert('Your Cart Is Empty :(')</script> -->
      <img src="<?php echo Mage::getImagePath('catalog/product/emptyCart.png') ?>">
      <a href="<?php echo $this->getUrl('catalog/product/all') ?>" style="position:absolute;top:80%;left:45%"><button
          type="button" class="btn btn-dark">keep shopping</button></a>

    <?php } ?>
  </div>
</div>