<?php 
$status = $this->status;
$id = $this->getRequest()->getparams("id");
$orderStatus = $this->getOrderCollection($id);
// print_r($orderStatus->getStatus());
// die;
$order = $this->getOrders();
// var_dump($id);
// print_r($order);
// echo "<br>";
$item = $this->getOrderItems($id);
// print_r($item);

?>
<div class="small-container">
            <h2 class="title" >Ordered Products</h2>
            <div class="row">
<?php foreach ($item as $_items) { 
    if($_items){
        foreach ($_items as $_item){
    ?>
                    <div class="col-4">
                        <a href="products-details.html"><img src="<?php echo Mage::getImagePath('catalog/product/'.$_item->getProduct()->getImageLink())?>"></a>
                        <a href="products-details.html"><h4>Product Name : <?php echo $_item->getProduct()->getName();?></h4></a>
                        <div class="rating">
                            <!--(before this added awesome4 cdn font link to the head)added a cdn link by searching font awesome4 icon and from the site  search the star entering the first option and getting a link of this fa-star*-->
                            <i class="fa fa-star" ></i>
                            <i class="fa fa-star" ></i>
                            <i class="fa fa-star" ></i>
                            <i class="fa fa-star-half-o" ></i>
                            <i class="fa fa-star-o" ></i>
                        </div>
                        <p>Price : <?php echo $_item->getProduct()->getPrice();?></p>
                        <p>Qty : <?php echo $_item->getQty();?></p>
                        <h4>
                            <form action="<?php echo Mage::getBaseUrl('admin/user/save')?>?id=<?php echo $_item->getOrderId();?>&action=admin" method="post">
                            <!-- <input type="text" value="<?php //echo $order->getOrderId()?>" hidden> -->
                            <select id="status" name="status" class="form-control">
                            <?php
                            foreach ($status as $key => $value) {
                                // echo '<option value="' . $value . '">' . $value . '</option>';
                                echo '<option value="' . $value . '" ' . ($orderStatus->getStatus() == $value ? 'selected' : '') . '>' . $value . '</option>';
                            }
                            ?>
                        </select>
                            <!-- <select name="status" id="status">
                                <option value="Pending">Pending</option>
                                <option value="Order confirmation">Order confirmation</option>
                                <option value="shipped">shipped</option>
                                 <option></option>
                                <option></option> -->
                            <!-- </select> -->
                            <input type="submit" name="submit" value="submit">

                     </form>
                        </h4>
                        <!-- <a href="<?php //echo Mage::getBaseUrl('admin/user/save')?>"><button> Update </button></a> -->
                    </div>
                    
<?php } } } ?>
</div>
        </div>
<?php
// foreach ($order as $_order) {
//     print_r($_order->getOrderId());
//     // print_r( $_order->getProduct());
// }

// foreach ($item as $_item) {
// //    print_r($_item->getProduct());
//     echo $_item->getProduct()->getName();
//     echo $_item->getQty();
// }

?>