<?php 
// print_r(Mage::getBaseUrl('catalog/category/view?id=1'));
$img = $this->getImageList();
// print_r($img);
// print_r(Mage::getImagePath('banner/images/'.$img[1]));
?>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css"
    />
   
  </head>
  <body>
    <div id="main">
    
      <div class="respo-nav">
        <i class="ri-close-fill"></i>
        <a href="">Store</a>
        <a href="">Mac</a>
        <a href="<?php echo $this->getUrl('catalog/category/view')?>">iPad</a>
        <a href="">iPhone</a>
        <a href="">Watch</a>
        <a href="">AirPods</a>
        <a href="">TV & Home</a>
        <a href="">Entertainment</a>
        <a href="">Accessories</a>
        <a href="">Support</a>
      </div>

      <div id="partO" class="part-1">
        <div class="text-part-1">
          <h1 style="position: absolute;top:10%;font-size:20vh;">iPhone 15 Pro</h1>
          <p style="position: absolute;top:20%;">New Camera. New Design. Newphoria.</p>
          <!-- <div class="link">
            <a href="">Learn More ></a>
            <a href="">Buy ></a>
          </div> -->
          <!-- <img src="images/resp2.jpg"> -->
          <img src="<?php echo Mage::getImagePath('banner/images/'.$img[4]);?>">
          <p>Titanium. So Strong. So Light. So Pro</p>
          <a href="">Learn More ></a>
            <a href="">Buy ></a>
          </div>
        </div>
      </div>
      <div class="part-1 part-2">
        <div class="">
          <!-- <img src="images/resp2.jpg"> -->
          <!-- <h1 style="color: aliceblue;">iPhone 15 Pro</h1>
          <p style="color: aliceblue;">New Camera. New Design. Newphoria.</p>
          <div class="link">
            <a href="">Learn More ></a>
            <a href="">Buy ></a>
          </div> -->
        </div>
      </div>
      <div class="part-1 part-3">
        <div class="text-part-1 text-part-3">
        <img src="<?php echo Mage::getImagePath('banner/images/'.$img[8]);?>">
        <img src="<?php echo Mage::getImagePath('banner/images/'.$img[10]);?>">
        
          <p>Titanium. So Strong. So Light. So Pro</p>
          <div class="link">
            <a href="">Learn More ></a>
            <a href="">Buy ></a>
          </div>
        </div>
      </div>
      <div class="part-4">
        <div class="part-1 part-4-1">
          <div class="text-part-1 text-part-3">
            <img src="images/4-1-1.png" alt="" />
            <!-- <p>Titanium. So Strong. So Light. So Pro</p>
            <div class="link">
              <a href="">Learn More ></a>
              <a href="">Buy ></a> -->
            </div>
          </div>
        </div>
        <div class="part-1 part-4-2">
          <div class="text-part-1 text-part-3">
          <img src="<?php echo Mage::getImagePath('banner/images/'.$img[9]);?>">
      
            <!-- <img src="images/4-2-1.png" alt="" />
            <p>Titanium. So Strong. So Light. So Pro</p>
            <div class="link">
              <a href="">Learn More ></a>
              <a href="">Buy ></a>
            </div> -->
          </div>
        </div>
      </div>
      <div class="part-4">
        <div class="part-1 part-4-1">
          <div class="text-part-1 text-part-3">
            <!-- <img src="images/4-1-1.png" alt="" />
            <p>Titanium. So Strong. So Light. So Pro</p>
            <div class="link">
              <a href="">Learn More ></a>
              <a href="">Buy ></a>
            </div> -->
          </div>
        </div>
        <div class="part-1 part-4-2">
          <div class="text-part-1 text-part-3">
          <img src="<?php echo Mage::getImagePath('banner/images/'.$img[10]);?>">
            <p>Titanium. So Strong. So Light. So Pro</p>
            <!-- <div class="link">
              <a href="">Learn More ></a>
              <a href="">Buy ></a>
            </div> -->
          </div>
        </div>
      </div>
      <!-- <div class="part-4">
        <div class="part-1 part-4-1">
          <div class="text-part-1 text-part-3">
            <img src="images/4-1-1.png" alt="" />
            <p>Titanium. So Strong. So Light. So Pro</p>
            <div class="link">
              <a href="">Learn More ></a>
              <a href="">Buy ></a>
            </div>
          </div>
        </div>
        <div class="part-1 part-4-2">
          <div class="text-part-1 text-part-3">
            <img src="images/4-2-1.png" alt="" />
            <p>Titanium. So Strong. So Light. So Pro</p>
            <div class="link">
              <a href="">Learn More ></a>
              <a href="">Buy ></a>
            </div>
          </div>
        </div>
      </div> -->
      <div class="slider-part">
        <div class="swiper mySwiper">
            <div class="swiper-wrapper">
              <div class="swiper-slide swiper-1">
                <img src="<?php echo Mage::getImagePath('banner/images/'.$img[0]);?>">
              </div>
              <div class="swiper-slide swiper-2">
              <img src="<?php echo Mage::getImagePath('banner/images/'.$img[1]);?>">
              </div>
              <div class="swiper-slide swiper-3">
              <img src="<?php echo Mage::getImagePath('banner/images/'.$img[2]);?>">
              </div>
              <div class="swiper-slide swiper-4">
              <img src="<?php echo Mage::getImagePath('banner/images/'.$img[3]);?>">
              </div>
              <div class="swiper-slide swiper-5">
              <img src="<?php echo Mage::getImagePath('banner/images/'.$img[5]);?>">
              </div>
              <div class="swiper-slide swiper-6">
              <img src="<?php echo Mage::getImagePath('banner/images/'.$img[6]);?>">
              </div>
            </div>
            <div class="swiper-button-next">
              <!-- <img src="images/4.jpg"> -->
            </div>
    <div class="swiper-button-prev"></div>
            <div class="swiper-pagination"></div>
          </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js"></script>
    <script>
      var swiper = new Swiper(".mySwiper", {
    slidesPerView: 1.5,
    centeredSlides: true,
    spaceBetween: 30,
    autoplay: {
        delay: 3500,
        disableOnInteraction: false,
      },
    pagination: {
      el: ".swiper-pagination",
      clickable: true,
    },
    navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
      },
    loop: true,
  });


var menu = document.querySelector(".ri-menu-3-line");
var clo = document.querySelector(".ri-close-fill");
var nav = document.querySelector(".respo-nav");

menu.addEventListener("click",function(){
      nav.style.top = "0%";
})

clo.addEventListener("click",function(){
  nav.style.top = "-120%";
})

var store = document.querySelector("#store");
var subMenu = document.querySelector(".submenu");

store.addEventListener("mousemove", function(){
  subMenu.style.top = "5%"
})

store.addEventListener("mouseleave", function(){
  subMenu.style.top = "-100%"
})

    </script>
  </body>

