<?php 
$productCollection = $this->getProductCollection();
?>


<h1 class="title">Apple Products</h1>
    <div class="product-grid-container">
    <?php foreach ($productCollection->getData() as $product) { ?>
        <?php //echo $product->getProductId() ?>
        <div class="product-container">
            <!-- <div class="product-image-wrapper">
                </div> -->
               <a href="<?php echo $this->getUrl('catalog/product/view') . '?id=' . $product->getProductId()?>"> <img src="<?php echo Mage::getImagePath("catalog/product/" . $product->getImageLink()) ?>" alt="" class="product-image"></a>
            <div class="product-info-container">
                <span class="product-seller">Krey Academy</span>
                <h3 class="product-title"><?php echo $product->getName(); ?></h3>
                <h3 class="product-price">Rs. <?php echo $product->getPrice(); ?></h3>
<!-- 
                <form action="<?php //echo $this->getUrl('sales/quote/add/') . '?id=' . $product->getProductId()?>" method="post">
                <input type="number" name="cart[qty]" class="qty" value=1 min="1" hidden>
                <button type="submit" style="
    background-color: green;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    font-size: 16px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    cursor: pointer;
">Add to Cart</button></form> -->
            </div>
        </div>
    
    <?php } ?>
    </div>