<?php
$obj = $this->getCustomerOrder();
// var_dump(Mage::getSingleton('sales/order')->getItemCollection($obj));
// die;
?>

<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-xl-6 col-md-12">
                <div class="card user-card-full">
                    <div class="row m-l-0 m-r-0">
                        <div class="col-sm-8">
                            <div class="card-block">
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Information</h6>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Email</p>
                                        <h6 class="text-muted f-w-400">rntng@gmail.com</h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <!-- <p class="m-b-10 f-w-600">Phone</p>
                                                                        <h6 class="text-muted f-w-400">98979989898</h6> -->
                                    </div>
                                </div>
                                <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Orders</h6>
                                <div class="row">
                                    <?php foreach ($obj as $value) { ?>
                                        <a href="<?php echo $this->getUrl('catalog/product/view?id=' . $value->getItemCollection()->getProductId()); ?>"
                                            style="text-decoration:none;color:#000">
                                            <div class="col-sm-6"
                                                style="border-bottom: 1px solid Black;margin-bottom: 30px;">
                                                <p class="m-b-10 f-w-600">Status :
                                                    <?php echo $value->getStatus(); ?>
                                                </p>
                                                <h6 class="text-muted f-w-400">Product Name :
                                                    <?php echo $value->getItemCollection()->getProductName(); ?>
                                                </h6>
                                            </div>
                                        </a>
                                    <?php } ?>


                                </div>
                                <div class="col-sm-6">
                                    <a href="<?php echo $this->getUrl('customer/account/logout'); ?>"><button
                                            type="button" class="btn btn-dark">Logout</button></a>
                                    <!-- <p class="m-b-10 f-w-600">Most Viewed</p>
                                                                        <h6 class="text-muted f-w-400">Dinoter husainm</h6> -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>