<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
        <title>Product Information</title>
        <link
      href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css"
    />
        <?php echo $this->getChildHtml('head'); ?>
    </head>

    <body >
        <!-- <h1>Good Day ! Hope This Day Brings You New Joy(❁´◡`❁)</h1> -->
        <div>
            <?php echo $this->getChildHtml('header'); ?>
        </div>
        
     
        <div>
            <?php echo $this->getChildHtml('content'); ?>
        </div>
        <div>
            <?php echo $this->getChildHtml('footer'); ?>
        </div>
    </body>

</html>